set(ARDUINO_PROTOCOL "arduino")
set(ARDUINO_BOARD "standard")
set(ARDUINO_MCU "atmega328p")
set(ARDUINO_FCPU "16000000")
set(ARDUINO_UPLOAD_SPEED "115200")
set(ARDUINO_PORT "/dev/ttyACM0")
set(ARDUINO_ROOT "$ENV{HOME}/opt/arduino")
set(CMAKE_C_COMPILER "${ARDUINO_ROOT}/hardware/tools/avr/bin/avr-gcc")
set(CMAKE_CXX_COMPILER "${ARDUINO_ROOT}/hardware/tools/avr/bin/avr-g++")
set(ARDUINO_OBJCOPY "${ARDUINO_ROOT}/hardware/tools/avr/bin/avr-objcopy")
set(ARDUINO_AVRDUDE "${ARDUINO_ROOT}/hardware/tools/avr/bin/avrdude")
include(${CMAKE_SOURCE_DIR}/scripts/libarduino_uno.cmake)